version: 2.1
orbs:
    browser-tools: circleci/browser-tools@1.4.2
jobs:
    build:
        docker:
            - image: cimg/node:16.19.1-browsers
        working_directory: ~/doc-it-dev
        environment:
            - MASTER_BRANCH: master
            - DEV_BRANCH: dev
            - DEV_TARGET: https://github.com/brightlayer-ui-dev/brightlayer-ui-dev.github.io
            - MASTER_TARGET: https://github.com/brightlayer-ui/brightlayer-ui.github.io
            - GH_EMAIL: brightlayer-ui@eaton.com
            - GH_NAME: Brightlayer UI Agent
        steps:
            - checkout
            - browser-tools/install-browser-tools
            - restore_cache:
                  keys:
                      - v3-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Install dependencies
                  command: |
                      yarn install
                      yarn upgrade @brightlayer-ui/icons-mui
            - save_cache:
                  paths:
                      - node_modules
                  key: v3-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: yarn lint
            - run:
                  name: Run tests
                  command: yarn test
            - run:
                  name: Verify Markdown Hyperlinks
                  command: |
                      yarn check:links-ci
            # - run:
            #      name: Run Cypress
            #      command: |
            #          if [ $CIRCLE_BRANCH == $MASTER_BRANCH ] || [ $CIRCLE_BRANCH == $DEV_BRANCH ]; then
            #          yarn cytest
            #          fi
            - run:
                  name: Deploy
                  command: |
                      if [ $CIRCLE_BRANCH == $MASTER_BRANCH ] || [ $CIRCLE_BRANCH == $DEV_BRANCH ]; then
                        git config --global user.email "$GH_EMAIL"
                        git config --global user.name "$GH_NAME"
                        
                        if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then
                          git clone $MASTER_TARGET out
                        else
                          git clone $DEV_TARGET out
                        fi

                        cd out
                        git rm -rf .
                        cd ..

                        # Copy the correct Google Analytics files (master/dev)
                        if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]
                        then
                          yarn ga:prod
                        elif [ $CIRCLE_BRANCH == $DEV_BRANCH ]
                        then
                          yarn ga:dev
                        fi

                        yarn build

                        cp -a build/. out/.
                        cd out

                        git add -A
                        git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
                        git push
                      fi
